default: &default
  adapter: mysql2
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: usda_development
