default: &default
  host: bahgsausda.cp5qykdsxe3g.us-east-1.rds.amazonaws.com
  adapter: mysql2
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  pool: 3306
  timeout: 5000

development:
  <<: *default
  database: usda
